generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: rhoas-realms
    files:
      - data/rhoas-kafka-sre-realm.json
      - data/rhoas-realm.json

resources:
  - deployment.yaml
  - service.yaml
