apiVersion: v1
kind: Service
metadata:
  name: cos-fleet-manager-kc
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cos-fleet-manager-kc
