apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cos-fleet-manager-db-volume-claim
  labels:
    app: cos-fleet-manager-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G