apiVersion: v1
kind: Service
metadata:
  name: cos-fleet-manager-db
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: cos-fleet-manager-db
