{
 "title": "CamelK Specific Connectors",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_id",
    "query": {
     "query": "label_values(container_network_receive_bytes_total{name=~\".*_mctr-.*\"}, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(application_camel_context_status{cluster_id=\"$cluster_id\"}, namespace)"
    }
   },
   {
    "name": "connector_id",
    "label": "Connector ID",
    "query": {
     "query": "label_values(application_camel_context_status{cluster_id=\"$cluster_id\",namespace=\"$namespace\"}, connector_id)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(application_camel_context_status{cluster_id=\"$cluster_id\",namespace=\"$namespace\",connector_id=\"$connector_id\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time Since Creation",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_context_uptime_seconds{cluster_id=\"$cluster_id\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "description": "Current Memory Usage",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(vendor_memoryPool_usage_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"})*100/sum(vendor_memoryPool_usage_max_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "stat",
   "description": "Exchange Overview",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_context_exchanges_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Exchanges Total"
    },
    {
     "expr": "application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Exchanges Completed"
    },
    {
     "expr": "application_camel_context_exchanges_failed_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Exchanges Failed"
    },
    {
     "expr": "application_camel_context_exchanges_inflight_count{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Exchanges Inflight"
    }
   ]
  },
  {
   "title": "Total Routes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_count{cluster_id=\"$cluster_id\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Connector Type",
   "type": "stat",
   "description": "Connector Type of the Connector.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_count{cluster_id=\"$cluster_id\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Connector ID",
   "type": "stat",
   "description": "Connector Id for the connector.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_count{cluster_id=\"$cluster_id\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "description": "Namespace the Connector belongs to.",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_count{cluster_id=\"$cluster_id\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Deployment ID",
   "type": "stat",
   "description": "Deployment ID for the Connector.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_route_count{cluster_id=\"$cluster_id\",namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  { "title": "Camel specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Exchange Processing Time",
   "type": "timeseries",
   "description": "Increase in the Exchange processing time series.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "increase(application_camel_exchange_processing_seconds_count{cluster_id=\"$cluster_id\",namespace=\"$namespace\",pod=\"$pod\"}[60m])",
     "legendFormat": "Rate of increase in Exchange Processing Time"
    }
   ]
  },
  {
   "title": "Exchanges Completed",
   "type": "timeseries",
   "description": "Increase in the Exchange Completion Rate.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "increase(application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\",pod=\"$pod\"}[60m])",
     "legendFormat": "{{camelContext}}"
    }
   ]
  },
  {
   "title": "Exchange Processing Rate",
   "type": "timeseries",
   "description": "Camel Exchange Processing Rate Per Second.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "application_camel_exchange_processing_rate_per_second{cluster_id=\"$cluster_id\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Exchange processing rate per second"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Vendor CPU",
   "type": "timeseries",
   "description": "CPU Utilization for the Connector.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "vendor_cpu_systemCpuLoad_percent{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "System Load Percent"
    }
   ]
  },
  {
   "title": "Base CPU",
   "type": "timeseries",
   "description": "CPU Utilization for the Connector.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Process Load Percent"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "description": "Load Average for the Connector.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "System Load Average"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Vendor Memory NonHeap",
   "type": "timeseries",
   "description": "Used vs Committed (Non-Heap) Memory for the Connector.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "vendor_memory_usedNonHeap_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memory_committedNonHeap_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Vendor Memory Heap",
   "type": "timeseries",
   "description": "Used vs Maximum (Heap) Memory for the Connector.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "sum(vendor_memoryPool_usage_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(vendor_memoryPool_usage_max_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Base Memory Heap",
   "type": "timeseries",
   "description": "Used vs Committed vs Maximum Memory for the Connector.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "base_memory_committedHeap_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "base_memory_maxHeap_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Network I/O Pressure",
   "type": "timeseries",
   "description": "Network packets received vs transmitted for the Connectors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\", name=~\".*_mctr-.*\"}[10m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\", pod=\"$pod\", name=~\".*_mctr-.*\"}[10m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}