{
 "title": "Data Plane | Cluster view",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "query": {
     "query": "label_values(container_network_receive_bytes_total{name=~\".*_mctr-.*\"}, cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_network_receive_bytes_total{cluster_id=\"$cluster_id\", name=~\".*_mctr-.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connectors Count (selected time)",
   "type": "stat",
   "description": "Total Connectors, CamelK Connectors vs Debezium Connectors running in the selected time range.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(up{container=\"integration\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Total Connectors"
    },
    {
     "expr": "count(max_over_time(application_camel_context_status{camelContext=\"camel-1\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "CamelK Connectors"
    },
    {
     "expr": "sum(max_over_time(up{container=\"integration\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range])) - count(max_over_time(application_camel_context_status{camelContext=\"camel-1\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Debezium connectors"
    }
   ]
  },
  {
   "title": "CamelK Connectors Types",
   "type": "piechart",
   "description": "Count of the types of CamelK Connectors for a specific cluster's namespace.",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "count by(connector_type) (max_over_time(application_camel_context_status{cluster_id=\"$cluster_id\", namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connectors Availability (selected time)",
   "type": "gauge",
   "description": "The percentage of time that the Connectors are available in the selected time range.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(up{container=\"integration\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range])) / sum(max_over_time(up{container=\"integration\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range])) * 100"
    }
   ]
  },
  {
   "title": "Connectors Running / Crashing",
   "type": "timeseries",
   "description": "CamelK Connectors, Debezium Connectors, and crashing Connectors over time. Crashing connectors are only shown when they are crashing(connectors that successfully got created previously and now crashing). ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{container=\"integration\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[10m]) >3)",
     "legendFormat": "Connectors Failing"
    },
    {
     "expr": "count(application_camel_context_status{camelContext=\"camel-1\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "CamelK Connectors"
    },
    {
     "expr": "sum(up{container=\"integration\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}) - count(application_camel_context_status{camelContext=\"camel-1\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Debezium Connectors"
    }
   ]
  },
  { "title": "CamelK Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Exchanges Count (selected time)",
   "type": "stat",
   "description": "Total, Completed, Failed, and Currently Inflight Exchanges for all the CamelK Connectors.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range])) - sum(min_over_time(application_camel_context_exchanges_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range])) - sum(min_over_time(application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_failed_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range])) - sum(min_over_time(application_camel_context_exchanges_failed_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(application_camel_context_exchanges_inflight_count{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Inflight Currently"
    }
   ]
  },
  {
   "title": "Exchanges Processed (selected time)",
   "type": "gauge",
   "description": "Percentage of exchanges completed in the selected time range.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range])) / sum(max_over_time(application_camel_context_exchanges_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[$__range])) * 100"
    }
   ]
  },
  {
   "title": "No. of Exchanges",
   "type": "timeseries",
   "description": "Exchanges Quantitative Information over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(application_camel_context_exchanges_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(application_camel_context_exchanges_completed_total{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Running CamelK Connectors",
   "type": "table",
   "description": "CamelK Connectors, their respective Namespace, and their time since creation. Click on the connector to see that connector's detailed dashboard. Filter column using the Filter option next to the column header.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "application_camel_context_status{camelContext=\"camel-1\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}"
    },
    {
     "expr": "application_camel_context_uptime_seconds{cluster_id=\"$cluster_id\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KameletBinding Reconciliation Durations",
   "type": "timeseries",
   "description": "The average rate of increase of the time series for the KameletBindings.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (result) (\n  rate(camel_k_reconciliation_duration_seconds_count{kind=\"KameletBinding\",cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\"}[5m])\n)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "IntegrationKit Reconciliation Durations",
   "type": "timeseries",
   "description": "The average rate of increase of the time series for the IntegrationKit.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (result) (\n  rate(camel_k_reconciliation_duration_seconds_count{kind=\"IntegrationKit\",cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\"}[5m])\n)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Integration Reconciliation Durations",
   "type": "timeseries",
   "description": "The average rate of increase of the time series for the Integration.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (result) (\n  rate(camel_k_reconciliation_duration_seconds_count{kind=\"Integration\",cluster_id=\"$cluster_id\",exported_namespace=\"$namespace\"}[5m])\n)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Debezium Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Debezium / Failed Reconciliation per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_failed_total{cluster_id=\"$cluster_id\"}[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Network I/O Pressure",
   "type": "timeseries",
   "description": "Sum of Network packets received vs transmitted for all the Connectors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".*_mctr-.*\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[10m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{name=~\".*_mctr-.*\",cluster_id=\"$cluster_id\",namespace=\"$namespace\"}[10m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Vendor Memory NonHeap",
   "type": "timeseries",
   "description": "Sum of used Memory vs Committed (Non-Heap) for all the Connectors.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vendor_memory_usedNonHeap_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(vendor_memory_committedNonHeap_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Vendor Memory Heap",
   "type": "timeseries",
   "description": "Sum of used Memory vs Committed (Heap) for all the Connectors.",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(vendor_memoryPool_usage_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(vendor_memoryPool_usage_max_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Base Memory Heap",
   "type": "timeseries",
   "description": "Sum of Used vs Committed vs Maximum Memory for all the Connectors.",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(base_memory_usedHeap_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(base_memory_committedHeap_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(base_memory_maxHeap_bytes{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Vendor CPU",
   "type": "timeseries",
   "description": "Sum of the CPU Utilization for all the Connectors.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(vendor_cpu_systemCpuLoad_percent{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "System Load Percent"
    }
   ]
  },
  {
   "title": "Base CPU",
   "type": "timeseries",
   "description": "Sum of the CPU Utilization for all the Connectors.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(base_cpu_processCpuLoad_percent{cluster_id=\"$cluster_id\",namespace=\"$namespace\"})",
     "legendFormat": "Process Load Percent"
    }
   ]
  }
 ]
}