{
 "title": "Data-plane SLO",
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Data Plane SLO Panel guides",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "## Availability\n* This panel shows the Availability for each individual Connector cluster, including the cluster id and SLO percentage.\n* Note that a Connector instance is evaluated for its availability only if it has been successfully configured and is able to startup once.\n* Can be filtered by Connector SLO percenatges, cluster Id and rolling window.\n* The SLO threshold is 99.5%, which is indicated by the horizontal red line.\n* You can click on an individual Connector cluster in the legend to filter the view to just that Connector cluster.\n\n## Remaining Error Budget (Availability)\n* This panel shows the Remaining Error Budget for each individual Connector cluster, including the cluster id.\n* Can be filtered by Remaining Error Budget percenatges, cluster Id and rolling window.\n* You can click on an individual Connector cluster in the legend to filter the view to just that Connector cluster.\n"
   }
  },
  {
   "title": "Data Plane SLO Panel guides",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "## Data Success Rate\n* This panel shows a Exchanges Success rate for each individual Connector cluster, including the cluster id and SLO percentage.\n* The rate is calculated using the data (sent or retrieved) to or from a third-party system.\n* Can be filtered by Connector SLO percenatges, cluster Id and rolling window.\n* The SLO threshold is 99.5%, which is indicated by the horizontal red line.\n* You can click on an individual Connector cluster in the legend to filter the view to just that Connector cluster.\n\n## Remaining Error Budget (Data)\n* This panel shows the Remaining Error Budget for each individual Connector cluster, including the cluster id.\n* Can be filtered by Remaining error budget percenatges, cluster Id and rolling window.\n* You can click on an individual Connector cluster in the legend to filter the view to just that Connector cluster.\n"
   }
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\"}[28d])) by (cluster_id) /\n( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\"}[28d])) by (cluster_id) + sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\"}[28d])) by (cluster_id) ) ) * 100",
     "legendFormat": "Cluster ID: {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Remaining Error Budget (Availability)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_min(( ( ( 0.005 * ( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\"}[28d])) by (cluster_id) + sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\"}[28d])) by (cluster_id) ) ) - sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\"}[28d])) by (cluster_id) ) / ( 0.005 * ( sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"ready\"}[28d])) by (cluster_id) + sum(rate(cos_fleetshard_sync_connector_state_count_total{cos_connector_state=\"failed_but_ready\"}[28d])) by (cluster_id) ) ) ) * 100, 0)",
     "legendFormat": "Cluster ID: {{cluster_id}}"
    }
   ]
  },
  {
   "title": "Data Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n( sum(rate(application_camel_context_exchanges_completed_total[28d])) by (cluster_id)\n/\n sum(rate(application_camel_context_exchanges_total[28d])) by (cluster_id) \n) * 100",
     "legendFormat": "Cluster ID:{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Remaining Error Budget (Data)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_min(( ( (sum(rate(application_camel_context_exchanges_total[28d])) by (cluster_id) * 0.005) - sum(rate(application_camel_context_exchanges_failed_total[28d])) by (cluster_id) ) / (sum(rate(application_camel_context_exchanges_total[28d])) by (cluster_id) * 0.005) ) * 100, 0)",
     "legendFormat": "Cluster ID:{{cluster_id}}"
    }
   ]
  }
 ]
}