generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cos-fleet-manager-config
    files:
      - data/connectors-quota-configuration.yaml
      - data/jwks-file.json

resources:
  - sa.yaml
  - deployment.yaml
  - service.yaml
