apiVersion: template.openshift.io/v1
kind: Template
name: connector-metadata-debezium
metadata:
  name: connector-metadata-debezium
  annotations:
    openshift.io/display-name: Cos Fleet Manager Debezium Connectors Metadata
    description: List of available debezium connectors metadata
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: connector-metadata-debezium
      annotations:
        qontract.recycle: "true"
        openshift.io/display-name: Cos Fleet Manager Debezium Connectors Metadata
        description: List of available debezium connectors metadata
    data:
      connector-metadata-debezium.yaml: |-
        ---
        - id: debezium-mongodb
          labels:
            - source
            - debezium
            - mongodb
            - category-database
            - category-change-data-capture
          annotations:
            cos.bf2.org/pricing-tier: plus
        - id: debezium-mysql
          labels:
            - source
            - debezium
            - mysql
            - category-database
            - category-change-data-capture
          annotations:
            cos.bf2.org/pricing-tier: plus
        - id: debezium-postgres
          labels:
            - source
            - debezium
            - postgres
            - category-database
            - category-change-data-capture
          annotations:
            cos.bf2.org/pricing-tier: plus
        - id: debezium-sqlserver
          labels:
            - source
            - debezium
            - sqlserver
            - category-database
            - category-change-data-capture
          annotations:
            cos.bf2.org/pricing-tier: plus
