---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: observability-remote-write-proxy-oidc-secret
  annotations:
    description: "Observability Remote Write Proxy OIDC secret"
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: observability-remote-write-proxy-oidc-config
  data:
    oidc-config: "${OBSERVABILITY_REMOTE_WRITE_PROXY_OIDC_CONFIG}"

parameters:
- name: OBSERVABILITY_REMOTE_WRITE_PROXY_OIDC_CONFIG
  description: >-
    Base64 encoded Observability Remote Write Proxy OIDC configuration.
    It should contain the YAML contents. See
    https://github.com/bf2fc6cc711aee1a0c2a/observability-remote-write-proxy
    for details on the configuration format.
  required: true
