---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: cos-fleet-manager-secrets
  annotations:
    description: "Kafka Service Fleet Manager Secrets"
parameters:

- name: DATABASE_HOST
  description: Hostname for the database server.
  value: cos-fleet-manager-db

- name: DATABASE_PORT
  description: Port of the database server.
  value: "5432"

- name: DATABASE_NAME
  description: Name for the database in the server.
  value: cos-fleet-manager

- name: DATABASE_USER
  description: User for the database server.
  value: ocm

- name: DATABASE_PASSWORD
  description: Password for the database user.
  value: TheBlurstOfTimes

- name: OCM_SERVICE_CLIENT_ID
  description: Client id used to interact with other UHC services

- name: OCM_SERVICE_CLIENT_SECRET
  description: Client secret used to interact with other UHC services

- name: OCM_SERVICE_TOKEN
  description: Offline token used to interact with other UHC services

- name: OBSERVATORIUM_SERVICE_TOKEN
  description: Offline token used to interact with other OBSERVATORIUM services

- name: SENTRY_KEY
  description: Private key used in Sentry DSN

- name: AWS_ACCESS_KEY
  description: AWS access key used to create CCS clusters

- name: AWS_ACCOUNT_ID
  description: AWS account id used to create CCS clusters

- name: AWS_SECRET_ACCESS_KEY
  description: AWS secret access key used to create CCS clusters

- name: ROUTE53_ACCESS_KEY
  description: AWS route 53 access key for creating CNAME records

- name: ROUTE53_SECRET_ACCESS_KEY
  description: AWS route 53 secret access key for creating CNAME records

- name: VAULT_ACCESS_KEY
  description: AWS secrets manager access key

- name: VAULT_SECRET_ACCESS_KEY
  description: AWS secrets manager secret access key

- name: MAS_SSO_CLIENT_ID
  description: Client id used to interact with mas sso

- name: MAS_SSO_CLIENT_SECRET
  description: Client secret used to interact with mas sso

- name: MAS_SSO_CRT
  description: tls certificate of the mas sso instance

- name: OBSERVABILITY_RHSSO_LOGS_CLIENT_ID
  description: Red Hat SSO Logs client id for observability stack

- name: OBSERVABILITY_RHSSO_METRICS_CLIENT_ID
  description: Red Hat SSO Metrics client id for the Observability stack

- name: OBSERVABILITY_RHSSO_LOGS_SECRET
  description: Red Hat SSO Logs secret for the Observability stack

- name: OBSERVABILITY_RHSSO_METRICS_SECRET
  description: Red Hat SSO Metrics secret for the Observability stack

- name: OBSERVABILITY_RHSSO_GRAFANA_CLIENT_ID
  description: Red Hat SSO Grafana client id for the Observability stack

- name: OBSERVABILITY_RHSSO_GRAFANA_CLIENT_SECRET
  description: Red Hat SSO Grafana secret for the Observability stack

objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: cos-fleet-manager-rds
  stringData:
    db.host: ${DATABASE_HOST}
    db.port: ${DATABASE_PORT}
    db.name: ${DATABASE_NAME}
    db.user: ${DATABASE_USER}
    db.password: ${DATABASE_PASSWORD}

- apiVersion: v1
  kind: Secret
  metadata:
    name: cos-fleet-manager
  stringData:
    ocm-service.clientId: ${OCM_SERVICE_CLIENT_ID}
    ocm-service.clientSecret: ${OCM_SERVICE_CLIENT_SECRET}
    ocm-service.token: ${OCM_SERVICE_TOKEN}
    observatorium.token: ${OBSERVATORIUM_SERVICE_TOKEN}
    sentry.key: ${SENTRY_KEY}
    aws.accesskey: ${AWS_ACCESS_KEY}
    aws.accountid: ${AWS_ACCOUNT_ID}
    aws.secretaccesskey: ${AWS_SECRET_ACCESS_KEY}
    vault.accesskey: ${VAULT_ACCESS_KEY}
    vault.secretaccesskey: ${VAULT_SECRET_ACCESS_KEY}
    keycloak-service.clientId: ${MAS_SSO_CLIENT_ID}
    keycloak-service.clientSecret: ${MAS_SSO_CLIENT_SECRET}
    osd-idp-keycloak-service.clientId: ${MAS_SSO_CLIENT_ID}
    osd-idp-keycloak-service.clientSecret: ${MAS_SSO_CLIENT_SECRET}
    keycloak-service.crt: ${MAS_SSO_CRT}
    aws.route53accesskey: ${ROUTE53_ACCESS_KEY}
    aws.route53secretaccesskey: ${ROUTE53_SECRET_ACCESS_KEY}

- apiVersion: v1
  kind: Secret
  metadata:
    name: cos-fleet-manager-observatorium-configuration-red-hat-sso
  stringData:
    logs.clientId: ${OBSERVABILITY_RHSSO_LOGS_CLIENT_ID}
    logs.clientSecret : ${OBSERVABILITY_RHSSO_LOGS_SECRET}
    metrics.clientId: ${OBSERVABILITY_RHSSO_METRICS_CLIENT_ID}
    metrics.clientSecret: ${OBSERVABILITY_RHSSO_METRICS_SECRET}
    grafana.clientId: ${OBSERVABILITY_RHSSO_GRAFANA_CLIENT_ID}
    grafana.clientSecret: ${OBSERVABILITY_RHSSO_GRAFANA_CLIENT_SECRET}