# This runs checks to verify if code is properly formatted and that tests (unit and integration against a mocked environment) are passing.
name: Build Binary

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint-test:
    name: "Build Binary"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Check out 
        uses: actions/checkout@v2
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TOKEN_USER: ${{ secrets.PERSONAL_ACCESS_TOKEN_USER }}
        run: |
          git config --global url."https://${TOKEN_USER}:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: "Build Binary" 
        env:
          OCM_ENV: integration
        run: |
          make goenv
          make binary
